<?php

namespace AppBundle\Repository;

/**
 * ShipToRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShipToRepository extends \Doctrine\ORM\EntityRepository
{
}
