<?php

namespace AppBundle\Repository;

/**
 * ShipOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShipOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
